### ISSUE TITLE
Local tests not working in Mac os x

### ISSUE THREAD

**Issue by gasproni** [spaconference/spa-website#56]
When I run the local build as per instructions in README.md, i.e., ```bundle exec jekyll serve —watch``` and then run the tests as ``` bundle exec htmlproofer --assume-extension --url-swap /spa2018: ./_site``` get the following errors:
```
Giovannis-MBP-2:spa-website giovanni$ bundle exec htmlproofer --assume-extension --url-swap /spa2018: ./_site
Running ["ScriptCheck", "ImageCheck", "LinkCheck"] on ["./_site"] on *.html... 


Checking 46 external links...
Ran on 26 files!


- ./_site/announcements/event-storming/ddd/sessions/2018/05/28/yves-event-storming.html
  *  External link http://localhost:4000/images/2018/yves1.jpg failed: 404 No error
  *  External link http://localhost:4000/images/2018/yves2.jpg failed: 404 No error
- ./_site/announcements/iot/2018/06/26/maisie-venus-iot.html
  *  External link http://localhost:4000/images/2018/distributed_biological.jpeg failed: 404 No error
- ./_site/announcements/keynotes/2018/02/28/launching-spa-2018.html
  *  External link http://localhost:4000/images/keynote_speakers/ChrisOdell.JPG failed: 404 No error
  *  External link http://localhost:4000/images/keynote_speakers/Jon_Skeet-13.jpg failed: 404 No error
  *  External link https://.eventbrite.co.uk failed: response code 0 means something's wrong.
             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
             Sometimes, making too many requests at once also breaks things.
             Either way, the return message (if any) from the server is: Couldn't resolve host name
- ./_site/announcements/keynotes/2018/04/10/alicia-keynote.html
  *  External link http://localhost:4000/images/keynote_speakers/Alicia_Carr.jpg failed: 404 No error
- ./_site/announcements/sketching/2018/06/03/rizwan-sketching.html
  *  External link http://localhost:4000/images/2018/rizwan-standing.jpg failed: 404 No error
  *  External link http://localhost:4000/images/2018/rizwan_banner.png failed: 404 No error
  *  External link https://spaconference.org/sessions/session768.html failed: 404 No error
- ./_site/book-now.html
  *  External link https://www.eventbrite.co.uk/e-tickets-42752231074 failed: 404 No error
- ./_site/sponsor.html
  *  External link https://www.spaconference.org/programme.html failed: 404 No error
htmlproofer 3.7.4 | Error:  HTML-Proofer found 12 failures!
```

**Comment by annashipman** [comment]
Just had a chance to look at this.

Most of these errors are because @NTCoding, when you added the images to the announcements pages, you used `| absolute_url` instead of `| relative_url`. You need to use the latter because the directory structure locally is different to on the server.

I'm not going to fix those because I'm going to remove this year's blog post for next year's site, so Nick (and anyone), just remember this when you add images next year (and maybe run the tests locally before pushing!)

The last three failures are interesting, it's dropped the `spa2018` from the URLs. This is because the test says  `--url-swap /spa2018: ./_site` which swaps it out anywhere in the URL. (So, for example, the ticket link which is actually `https://www.eventbrite.co.uk/e/spa2018-tickets-42752231074` becomes `https://www.eventbrite.co.uk/e-tickets-42752231074`, a 404).

We actually only want to swap out `/spa2018` when it appears at the beginning of the URL, so I've updated the documentation to make that clear (#61).

Once I've removed the blog posts, the tests should run locally. Feel free to confirm this @gasproni when you get a chance.

**Comment by NTCoding** [comment]
Hey folks,

Apologies in advance for any problems that may have arisen here. I don't remember all of the intricacies but there were a couple of issues I had to try and fix related to urls and I didn't realise I had broken stuff. As far as I was aware I was running all of the tests locally and on the few occasions I forgot I wasn't they would fail on travis so it wasn't possible to merge (I think).

I also changed that URL pattern so that it only replaces the /spa2018 if it's at the start of a URL as well https://github.com/spaconference/spa-website/commit/126e59c9ee69fc2bda7346e46cce39f100ee4ffe. I vaguely remember this problem occurring previously and I think there is some discussion in an email or pull request somewhere.

Next time I write an article I'll definitely go with the relative urls. If anything else needs fixing in the meantime just let me know and I'll be happy to investigate in further detail.

Thanks for letting me know and apologies for any time you have lost on my part.

**Comment by NTCoding** [comment]
Oh yes, I also remember now about running the tests. The reason I didn't change the config file was because I didn't want to change the Jenkins job. So I was using this command locally: ```bundle exec htmlproofer --assume-extension --url-swap ^/spa2018: ./_site```

**Comment by annashipman** [comment]
Ah right, OK, thanks! So the issue is just that, when you made the change `126e59c` you didn't also update the README where it says how to run the tests locally, so Gio was running the version without the `^` because he was following the README rather than just running `build.sh`.

Anyway, all fixed now. Ta.

**Comment by NTCoding** [comment]
Yeah I should have updated the readme. Sorry.
